# Generated by Django 5.2.7 on 2025-10-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Предсказанная цена')),
                ('confidence', models.FloatField(blank=True, null=True, verbose_name='Уверенность прогноза (0-1)')),
                ('model_version', models.CharField(max_length=50, verbose_name='Версия модели')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата предсказания')),
                ('feature_importance', models.JSONField(blank=True, default=dict, verbose_name='Важность признаков')),
                ('prediction_explanation', models.TextField(blank=True, verbose_name='Объяснение предсказания')),
            ],
            options={
                'verbose_name': 'Предсказание',
                'verbose_name_plural': 'Предсказания',
            },
        ),
    ]
